version: 2.1

aliases:
  - &workspace_root ~/workspace

  - &attach_workspace
     at: *workspace_root

  - &persist_to_workspace
    root: .
    paths:
      - .

  - &save_js_packages
    key: js-packages-v1-{{ .Branch }}-{{ checksum "/root/project/app/package-lock.json" }}-{{ checksum "/root/project/app/packages/t3n-components/package-lock.json" }}-{{ checksum "/root/project/app/packages/t3n-storybook/package-lock.json" }}-{{ checksum "/root/project/app/packages/t3n-styles/package-lock.json" }}
    paths:
      - /root/.npm

  - &restore_js_packages
    keys: 
      - js-packages-v1-{{ .Branch }}-{{ checksum "/root/project/app/package-lock.json" }}-{{ checksum "/root/project/app/packages/t3n-components/package-lock.json" }}-{{ checksum "/root/project/app/packages/t3n-storybook/package-lock.json" }}-{{ checksum "/root/project/app/packages/t3n-styles/package-lock.json" }}
      - js-packages-v1-{{ .Branch }}-
      - js-packages-v1-

orbs:
  docker-image: t3n/docker-image@1.0
  kubr: t3n/kubr@1.0

jobs:
  checkout_and_build:
    docker:
      - image: quay.io/yeebase/ci-build:7.2
    steps:
      - checkout

      - run: |
          npm install --unsafe-perm

      - run: |
          npm run build:styles
      
      - run: |
          npm run build:components
      
      - run: |
          npm run build:storybook

      - persist_to_workspace: *persist_to_workspace
  
  lint: 
    working_directory: *workspace_root
    docker:
      - image: quay.io/yeebase/ci-build:7.2
    steps:
      - attach_workspace: *attach_workspace
      - run: npm run lint:styles
      - run: npm run lint:components
      - run: npm run lint:storybook

  docker_build_and_push:
    working_directory: *workspace_root
    docker:
      - image: google/cloud-sdk
    steps:
      - attach_workspace: *attach_workspace
      - setup_remote_docker
      - docker-image/gcr-build-and-push:
          image: storybook

workflows:
  version: 2
  build_and_test:
    jobs:
      - checkout_and_build
      - lint:
          requires:
            - checkout_and_build
      - docker_build_and_push:
          filters:
            branches:
              only:
                - master
          context: google
          requires:
            - lint
      - kubr/deploy:
          deployment: Live
          filters:
            branches:
              only:
                - master
          context: kubr
          requires:
            - docker_build_and_push
            
  build_and_push_feature:
    jobs:
      - push_feature:
          type: approval
          filters:
            branches:
              only:
                - /feature.*/
      - checkout_and_build:
          filters:
            branches:
              only:
                - /feature.*/
          requires:
            - push_feature
      - docker_build_and_push:
          filters:
            branches:
              only:
                - /feature.*/
          context: google
          requires:
            - checkout_and_build